import 'package:flutter/material.dart';
import '../../../../core/theme/app_colors.dart';
import 'discover_program_model.dart';

const defaultDiscoverPrograms = <DiscoverProgram>[
  DiscoverProgram(
    id: 'prog_ppl',
    name: 'Push Pull Legs (PPL)',
    author: 'Coach Vince & Team',
    description:
        'Giáo án kinh điển và hiệu quả nhất để phát triển toàn diện kích thước cơ bắp và sức mạnh. Chia nhóm cơ đẩy (Ngực/Vai/Tay sau), kéo (Lưng/Tay trước) và Chân/Mông hợp lý.',
    coverImage:
        'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Intermediate',
    goals: ['Hypertrophy', 'Muscle Gain', 'Strength'],
    frequencyDays: 5,
    durationWeeks: 12,
    exerciseCount: 18,
    rating: 4.9,
    reviewCount: 342,
    popularityScore: 98,
    trendingScore: 99,
    equipment: ['Barbell', 'Dumbbells', 'Cable', 'Rack'],
    muscleGroups: [
      'Ngực',
      'Lưng',
      'Vai',
      'Tay trước',
      'Tay sau',
      'Đùi trước',
      'Mông'
    ],
    category: 'Hypertrophy',
    isFeatured: true,
    isTrending: true,
    accentColor: Color(0xFF4E78A5),
    weeklySchedule: [
      ProgramWeeklyDay(
        dayOfWeek: 1,
        dayName: 'Thứ 2',
        workoutName: 'PUSH A (Ngực, Vai, Tay sau)',
        isRestDay: false,
        muscleGroups: ['Ngực', 'Vai', 'Tay sau'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Barbell Bench Press',
              sets: 4,
              reps: '6-8',
              restSeconds: 120,
              muscle: 'Ngực'),
          ProgramWeeklyExercise(
              name: 'Incline Dumbbell Press',
              sets: 3,
              reps: '10-12',
              restSeconds: 90,
              muscle: 'Ngực trên'),
          ProgramWeeklyExercise(
              name: 'Overhead Press',
              sets: 3,
              reps: '8-10',
              restSeconds: 90,
              muscle: 'Vai'),
          ProgramWeeklyExercise(
              name: 'Tricep Rope Pushdown',
              sets: 3,
              reps: '12-15',
              restSeconds: 60,
              muscle: 'Tay sau'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 2,
        dayName: 'Thứ 3',
        workoutName: 'PULL A (Lưng xô, Tay trước)',
        isRestDay: false,
        muscleGroups: ['Lưng', 'Tay trước'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Conventional Deadlift',
              sets: 4,
              reps: '5',
              restSeconds: 180,
              muscle: 'Lưng'),
          ProgramWeeklyExercise(
              name: 'Lat Pulldown',
              sets: 4,
              reps: '10-12',
              restSeconds: 90,
              muscle: 'Cơ xô'),
          ProgramWeeklyExercise(
              name: 'Barbell Bent-Over Row',
              sets: 3,
              reps: '8-10',
              restSeconds: 90,
              muscle: 'Lưng giữa'),
          ProgramWeeklyExercise(
              name: 'Barbell Bicep Curl',
              sets: 3,
              reps: '12',
              restSeconds: 60,
              muscle: 'Tay trước'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 3,
        dayName: 'Thứ 4',
        workoutName: 'LEGS A (Đùi trước, Mông, Bắp chân)',
        isRestDay: false,
        muscleGroups: ['Đùi trước', 'Mông', 'Bắp chân'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Barbell Back Squat',
              sets: 4,
              reps: '6-8',
              restSeconds: 120,
              muscle: 'Đùi trước'),
          ProgramWeeklyExercise(
              name: 'Leg Press 45°',
              sets: 4,
              reps: '10-12',
              restSeconds: 90,
              muscle: 'Đùi trước'),
          ProgramWeeklyExercise(
              name: 'Romanian Deadlift',
              sets: 3,
              reps: '10-12',
              restSeconds: 90,
              muscle: 'Đùi sau'),
          ProgramWeeklyExercise(
              name: 'Standing Calf Raise',
              sets: 4,
              reps: '15',
              restSeconds: 60,
              muscle: 'Bắp chân'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 4,
        dayName: 'Thứ 5',
        workoutName: 'PUSH B (Ngực trên & Vai giữa)',
        isRestDay: false,
        muscleGroups: ['Ngực trên', 'Vai giữa', 'Cơ bụng'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Incline Dumbbell Press',
              sets: 4,
              reps: '8-10',
              restSeconds: 90,
              muscle: 'Ngực trên'),
          ProgramWeeklyExercise(
              name: 'Dumbbell Lateral Raise',
              sets: 4,
              reps: '15',
              restSeconds: 60,
              muscle: 'Vai giữa'),
          ProgramWeeklyExercise(
              name: 'Cable Chest Fly',
              sets: 3,
              reps: '12-15',
              restSeconds: 60,
              muscle: 'Ngực'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 5,
        dayName: 'Thứ 6',
        workoutName: 'PULL B & ARMS (Lưng dày & Cánh tay)',
        isRestDay: false,
        muscleGroups: ['Lưng', 'Tay'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Seated Cable Row',
              sets: 4,
              reps: '10-12',
              restSeconds: 90,
              muscle: 'Lưng'),
          ProgramWeeklyExercise(
              name: 'Hammer Curl',
              sets: 3,
              reps: '12',
              restSeconds: 60,
              muscle: 'Tay trước'),
          ProgramWeeklyExercise(
              name: 'Skull Crushers',
              sets: 3,
              reps: '12',
              restSeconds: 60,
              muscle: 'Tay sau'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 6,
        dayName: 'Thứ 7',
        workoutName: 'Nghỉ ngơi tích cực',
        isRestDay: true,
      ),
      ProgramWeeklyDay(
        dayOfWeek: 7,
        dayName: 'Chủ Nhật',
        workoutName: 'Nghỉ ngơi hoàn toàn',
        isRestDay: true,
      ),
    ],
  ),
  DiscoverProgram(
    id: 'prog_powerbuilding_5x',
    name: 'Powerbuilding 5x Heavy',
    author: 'Coach Zane',
    description:
        'Sự kết hợp đỉnh cao giữa sức mạnh nâng tạ nặng Big 3 của Powerlifting và thể tích bơm máu tạo khối cơ sắc nét của Bodybuilding.',
    coverImage:
        'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Advanced',
    goals: ['Powerbuilding', 'Strength', 'Hypertrophy'],
    frequencyDays: 5,
    durationWeeks: 10,
    exerciseCount: 22,
    rating: 4.8,
    reviewCount: 215,
    popularityScore: 92,
    trendingScore: 95,
    equipment: ['Barbell', 'Dumbbells', 'Rack', 'Plates'],
    muscleGroups: ['Toàn thân', 'Ngực', 'Lưng', 'Chân', 'Vai'],
    category: 'Powerbuilding',
    isFeatured: true,
    isTrending: true,
    accentColor: Color(0xFF557FA8),
    weeklySchedule: [
      ProgramWeeklyDay(
        dayOfWeek: 1,
        dayName: 'Thứ 2',
        workoutName: 'Heavy Bench Press & Chest Hypertrophy',
        isRestDay: false,
        muscleGroups: ['Ngực', 'Tay sau'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Barbell Bench Press',
              sets: 5,
              reps: '5',
              restSeconds: 180,
              muscle: 'Ngực'),
          ProgramWeeklyExercise(
              name: 'Incline Dumbbell Press',
              sets: 4,
              reps: '8-10',
              restSeconds: 90,
              muscle: 'Ngực trên'),
          ProgramWeeklyExercise(
              name: 'Chest Dips',
              sets: 3,
              reps: '10',
              restSeconds: 90,
              muscle: 'Ngực dưới'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 2,
        dayName: 'Thứ 3',
        workoutName: 'Heavy Squat & Quad Focus',
        isRestDay: false,
        muscleGroups: ['Đùi trước', 'Mông'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Barbell Back Squat',
              sets: 5,
              reps: '5',
              restSeconds: 180,
              muscle: 'Đùi trước'),
          ProgramWeeklyExercise(
              name: 'Leg Press 45°',
              sets: 4,
              reps: '10-12',
              restSeconds: 90,
              muscle: 'Đùi'),
          ProgramWeeklyExercise(
              name: 'Standing Calf Raise',
              sets: 4,
              reps: '15',
              restSeconds: 60,
              muscle: 'Bắp chân'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 3,
        dayName: 'Thứ 4',
        workoutName: 'Nghỉ ngơi hồi phục',
        isRestDay: true,
      ),
      ProgramWeeklyDay(
        dayOfWeek: 4,
        dayName: 'Thứ 5',
        workoutName: 'Heavy Deadlift & Back Thickness',
        isRestDay: false,
        muscleGroups: ['Lưng', 'Đùi sau'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Conventional Deadlift',
              sets: 5,
              reps: '3-5',
              restSeconds: 180,
              muscle: 'Lưng'),
          ProgramWeeklyExercise(
              name: 'Barbell Bent-Over Row',
              sets: 4,
              reps: '8',
              restSeconds: 90,
              muscle: 'Lưng giữa'),
          ProgramWeeklyExercise(
              name: 'Lat Pulldown',
              sets: 4,
              reps: '10',
              restSeconds: 90,
              muscle: 'Cơ xô'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 5,
        dayName: 'Thứ 6',
        workoutName: 'Overhead Press & Arm Pump',
        isRestDay: false,
        muscleGroups: ['Vai', 'Tay trước', 'Tay sau'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Overhead Barbell Press',
              sets: 5,
              reps: '5',
              restSeconds: 120,
              muscle: 'Vai'),
          ProgramWeeklyExercise(
              name: 'Dumbbell Lateral Raise',
              sets: 4,
              reps: '15',
              restSeconds: 60,
              muscle: 'Vai'),
          ProgramWeeklyExercise(
              name: 'Barbell Curl',
              sets: 4,
              reps: '10',
              restSeconds: 60,
              muscle: 'Tay trước'),
          ProgramWeeklyExercise(
              name: 'Skull Crushers',
              sets: 4,
              reps: '10',
              restSeconds: 60,
              muscle: 'Tay sau'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 6,
        dayName: 'Thứ 7',
        workoutName: 'Cardio & Abs',
        isRestDay: true,
      ),
      ProgramWeeklyDay(
        dayOfWeek: 7,
        dayName: 'Chủ Nhật',
        workoutName: 'Nghỉ ngơi hoàn toàn',
        isRestDay: true,
      ),
    ],
  ),
  DiscoverProgram(
    id: 'prog_womens_glute',
    name: "Women's Glute & Lower Body Focus",
    author: 'Coach Elena',
    description:
        'Chương trình chuyên biệt cho nữ giới tập trung phát triển cơ mông căng tròn, thon gọn đùi và định hình vòng eo con kiến.',
    coverImage:
        'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Beginner',
    goals: ['Muscle Gain', 'Fat Loss', 'General Fitness'],
    frequencyDays: 4,
    durationWeeks: 8,
    exerciseCount: 16,
    rating: 4.9,
    reviewCount: 418,
    popularityScore: 96,
    trendingScore: 98,
    equipment: ['Barbell', 'Dumbbells', 'Bands', 'Bench'],
    muscleGroups: ['Cơ mông', 'Đùi sau', 'Đùi trước', 'Cơ bụng'],
    category: 'Women',
    isFeatured: true,
    isTrending: true,
    accentColor: AppColors.statusRecovery,
    weeklySchedule: [
      ProgramWeeklyDay(
        dayOfWeek: 1,
        dayName: 'Thứ 2',
        workoutName: 'Glute Hypertrophy & Hip Thrust Day',
        isRestDay: false,
        muscleGroups: ['Cơ mông', 'Đùi sau'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Barbell Hip Thrust',
              sets: 4,
              reps: '10-12',
              restSeconds: 90,
              muscle: 'Mông'),
          ProgramWeeklyExercise(
              name: 'Romanian Deadlift',
              sets: 4,
              reps: '10-12',
              restSeconds: 90,
              muscle: 'Đùi sau'),
          ProgramWeeklyExercise(
              name: 'Bulgarian Split Squat',
              sets: 3,
              reps: '10 mỗi chân',
              restSeconds: 90,
              muscle: 'Mông'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 2,
        dayName: 'Thứ 3',
        workoutName: 'Upper Body Tone & Core',
        isRestDay: false,
        muscleGroups: ['Lưng', 'Vai', 'Bụng'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Lat Pulldown',
              sets: 4,
              reps: '12',
              restSeconds: 60,
              muscle: 'Lưng'),
          ProgramWeeklyExercise(
              name: 'Dumbbell Lateral Raise',
              sets: 4,
              reps: '15',
              restSeconds: 60,
              muscle: 'Vai'),
          ProgramWeeklyExercise(
              name: 'Plank',
              sets: 3,
              reps: '60s',
              restSeconds: 60,
              muscle: 'Bụng'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 3,
        dayName: 'Thứ 4',
        workoutName: 'Nghỉ ngơi hồi phục',
        isRestDay: true,
      ),
      ProgramWeeklyDay(
        dayOfWeek: 4,
        dayName: 'Thứ 5',
        workoutName: 'Quad & Glute Power',
        isRestDay: false,
        muscleGroups: ['Đùi trước', 'Mông'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Barbell Back Squat',
              sets: 4,
              reps: '8-10',
              restSeconds: 90,
              muscle: 'Đùi trước'),
          ProgramWeeklyExercise(
              name: 'Leg Press 45°',
              sets: 4,
              reps: '12',
              restSeconds: 90,
              muscle: 'Đùi'),
          ProgramWeeklyExercise(
              name: 'Cable Kickback',
              sets: 3,
              reps: '15 mỗi chân',
              restSeconds: 60,
              muscle: 'Mông'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 5,
        dayName: 'Thứ 6',
        workoutName: 'Full Body HIIT & Abs Burn',
        isRestDay: false,
        muscleGroups: ['Toàn thân', 'Cơ bụng'],
        exercises: [
          ProgramWeeklyExercise(
              name: 'Cable Woodchopper',
              sets: 3,
              reps: '15',
              restSeconds: 45,
              muscle: 'Bụng'),
          ProgramWeeklyExercise(
              name: 'Hanging Leg Raise',
              sets: 3,
              reps: '15',
              restSeconds: 45,
              muscle: 'Bụng'),
          ProgramWeeklyExercise(
              name: 'Incline Treadmill Walk',
              sets: 1,
              reps: '25 phút',
              restSeconds: 0,
              muscle: 'Cardio'),
        ],
      ),
      ProgramWeeklyDay(
        dayOfWeek: 6,
        dayName: 'Thứ 7',
        workoutName: 'Nghỉ ngơi tích cực',
        isRestDay: true,
      ),
      ProgramWeeklyDay(
        dayOfWeek: 7,
        dayName: 'Chủ Nhật',
        workoutName: 'Nghỉ ngơi hoàn toàn',
        isRestDay: true,
      ),
    ],
  ),
  DiscoverProgram(
    id: 'prog_gzcl_method',
    name: 'GZCL Method Linear Progression',
    author: 'Cody Lefever',
    description:
        'Cấu trúc 3 tầng Tier (T1 Mức tạ chính cực nặng, T2 Bổ trợ trung bình, T3 Cô lập thể tích) giúp người tập tiến bộ sức mạnh đều đặn.',
    coverImage:
        'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Intermediate',
    goals: ['Powerlifting', 'Strength'],
    frequencyDays: 4,
    durationWeeks: 12,
    exerciseCount: 15,
    rating: 4.9,
    reviewCount: 189,
    popularityScore: 90,
    trendingScore: 88,
    equipment: ['Barbell', 'Rack', 'Bench'],
    muscleGroups: ['Toàn thân', 'Ngực', 'Lưng', 'Chân'],
    category: 'Powerlifting',
    accentColor: AppColors.aiPurple,
  ),
  DiscoverProgram(
    id: 'prog_calisthenics',
    name: 'Bodyweight & Calisthenics Mastery',
    author: 'Coach Nolan',
    description:
        'Giáo án làm chủ sức mạnh trọng lượng cơ thể từ hít xà, chống đẩy đến các động tác kỹ thuật nâng cao.',
    coverImage:
        'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Beginner',
    goals: ['Bodyweight', 'Endurance', 'Mobility'],
    frequencyDays: 3,
    durationWeeks: 8,
    exerciseCount: 12,
    rating: 4.7,
    reviewCount: 95,
    popularityScore: 84,
    trendingScore: 82,
    equipment: ['Bodyweight', 'Pull-up Bar'],
    muscleGroups: ['Ngực', 'Lưng', 'Tay', 'Cơ bụng'],
    category: 'Bodyweight',
    accentColor: AppColors.primaryBlueLight,
  ),
  DiscoverProgram(
    id: 'prog_fat_loss_hiit',
    name: 'High Intensity Fat Loss & Conditioning',
    author: 'Coach Alex',
    description:
        'Đốt mỡ tối đa với các chuỗi bài tập cường độ cao kết hợp tạ đơn và tim mạch, duy trì trao đổi chất EPOC suốt 24 giờ sau tập.',
    coverImage:
        'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800&auto=format&fit=crop&q=80',
    difficulty: 'Intermediate',
    goals: ['Fat Loss', 'Conditioning', 'Endurance'],
    frequencyDays: 4,
    durationWeeks: 6,
    exerciseCount: 14,
    rating: 4.8,
    reviewCount: 154,
    popularityScore: 88,
    trendingScore: 86,
    equipment: ['Dumbbells', 'Rowing Machine', 'Treadmill'],
    muscleGroups: ['Toàn thân', 'Tim mạch', 'Cơ bụng'],
    category: 'Cardio & Fat Loss',
    accentColor: Color(0xFF183B63),
  ),
];
